version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=peaks
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD=10027563
  web:
    build: .
    command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=peaks
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD=10027563
    depends_on:
      - db