# Generated by Django 4.1.7 on 2023-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0002_rejectedconnexion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectedconnexion',
            options={'verbose_name': 'Rejected Connexion', 'verbose_name_plural': 'Rejected Connexions'},
        ),
        migrations.AlterField(
            model_name='rejectedconnexion',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rejectedconnexion',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
